version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: simple-gl-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: simple-gl-{{ checksum "pom.xml" }}
      - run: mvn package
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - package.json
            - target/js

  deploy:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - attach_workspace:
          at: ~/tmp/
      - run: mv package.json target/js
      - run: cd target/js
      - run: ls -ltr

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build