version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: workspace
          paths:
            - .

  test:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls node_modules