version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: node_modules
          paths:
            - .

  test:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - attach_workspace:
          at: node_modules
      - run: ls node_modules

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build