version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: simple-gl-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: simple-gl-{{ checksum "pom.xml" }}
      - run: mkdir -p target/classes/META-INF
      - run: mv LICENSE target/classes/META-INF
      - run: mv README.md target/classes/META-INF
      - run: mv package.json target/classes/META-INF
      - run: mvn -s .circleci/settings.xml deploy
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - target/classes/META-INF

  deploy:
    working_directory: ~/tmp/
    docker:
      - image: circleci/node:7
    steps:
      - attach_workspace:
          at: ~/tmp/
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run: mv target/classes/META-INF/* .
      - run:
          name: Update Version
          command: npm version 2.0.$CIRCLE_BUILD_NUM
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build