# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  dependencies:
    pre:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  deploy:
    steps:
      
    npm:
      tag: /v[0-9]+(\.[0-9]+)*/
      commands:
        - npm publish


        version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/simple-gl
    steps:
      - checkout
      - attach_workspace:
          at: ~/simple-gl
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - persist_to_workspace:
          root: .
          paths: .
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/simple-gl
    steps:
      - attach_workspace:
          at: ~/simple-gl
      - run: npm install
      - run: npm test
  release:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/simple-gl
    steps:
      - attach_workspace:
          at: ~/simple-gl
      - run: npm publish
workflows:
  version: 2
  test_and_release:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - hold
          filters:
            branches:
              only: master