version: 2
jobs:
  install:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/simple-gl
    steps:
      - checkout
      - attach_workspace:
          at: ~/simple-gl
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: .
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/simple-gl
    steps:
      - attach_workspace:
          at: ~/simple-gl
      - run: npm test
      - run: mkdir -p test-results && mv test-results.xml test-results
      - store_test_results:
          path: test-results
  release:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/simple-gl
    steps:
      - attach_workspace:
          at: ~/simple-gl
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run: cp package.json dist
      - run: cd dist && npm publish
workflows:
  version: 2
  test_and_release:
    jobs:
      - install
      - test:
          requires:
            - install
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - hold
          filters:
            branches:
              only: master
              