version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/simple-gl
    steps:
      - checkout
      - attach_workspace:
          at: ~/simple-gl
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - persist_to_workspace:
          root: .
          paths: .
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/simple-gl
    steps:
      - attach_workspace:
          at: ~/simple-gl
      - run: yarn install
      - run: yarn test
  release:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/simple-gl
    steps:
      - attach_workspace:
          at: ~/simple-gl
      - run: yarn install
      - run: yarn start release || true
workflows:
  version: 2
  test_and_release:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - hold
          filters:
            branches:
              only: master