version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Install Node Dependencies
          command: npm install
      - run:
          name: Transpile
          command: npm run build
      - run:
          name: Test
          command: npm test
      - run:
          name: Stage artifact
          command: mv package.json kotlin_build && mv LICENSE kotlin_build && mv README.md kotlin_build
      - run:
          name: npm Authentication
          command: cd kotlin_build && echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Set npm package version
          command: cd kotlin_build && npm version 2.0.$CIRCLE_BUILD_NUM
      - run:
          name: Release to npm
          command: cd kotlin_build && npm publish