version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Install Node Dependencies
          command: npm install
      - run:
          name: Transpile
          command: npm run build
      - run:
          name: Test
          command: npm test
      - run:
          name: npm Authentication
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Set npm package version
          command: npm version --no-git-tag-version -f 2.0.$CIRCLE_BUILD_NUM
      - run:
          name: Release to npm
          command: npm publish --access public