version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Install Node Dependencies
          command: npm install
      - run:
          name: Transpile
          command: npm run build
      - run:
          name: Test
          command: npm test
      - run:
          name: Stage artifact
          command: mv package.json bin/build && mv LICENSE bin/build && mv README.md bin/build
      - run:
          name: npm Authentication
          command: cd bin/build && echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Set npm package version
          command: cd bin/build && npm version 2.0.$CIRCLE_BUILD_NUM
      - run:
          name: Release to npm
          command: cd bin/build && npm publish